### ISSUE TITLE
Simple physics engine?

### ISSUE THREAD

**Issue by cliffordh** [spritewidget/spritewidget#12]
Does SpriteWidget include any simple physics, e.g. collision detection, gravity? If not, do you have any recommendations? Thanks.

**Comment by vlidholt** [comment]
@cliffordh There is a version of Box2D written in Dart that works well with SpriteWidget. https://pub.dartlang.org/packages/box2d

**Comment by spkingr** [comment]
How to add the box2d features to SpriteWidget? Is there any tutorial? Thanks.
