### ISSUE TITLE
On iOS whenever a system alert pops up. The handleEvent Call doesn't get called and sprite assert gets fired in error logs.

### ISSUE THREAD

**Issue by mjaffa-figure** [spritewidget/spritewidget#14]
Run your SpriteWidget scene, put an in app purchase dialog in your app, System alert will pop up to purchase. Dismiss the dialog. When you get back to your SpriteWidget scene your handleEvent callback never gets called and look in the logs and you see in somewhere in SPriteWidget before it gets to giving the scene the handleEvent call. The spriteBox is null.

**Comment by vlidholt** [comment]
I think this may have been fixed. Re-open if it's still an issue.
