### ISSUE TITLE
Error when running weather example.

### ISSUE THREAD

**Issue by Sacchid** [spritewidget/spritewidget#21]
Launching lib\main.dart on Pixel 2 in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...
I/FlutterActivityDelegate(11284): onResume setting current activity to this
I/FlutterActivityDelegate(11330): onResume setting current activity to this
Built build\app\outputs\apk\debug\app-debug.apk (25.9MB).
Installing build\app\outputs\apk\app.apk...
I/FlutterActivityDelegate(11476): onResume setting current activity to this
I/flutter (11476): ══╡ EXCEPTION CAUGHT BY SERVICES ╞══════════════════════════════════════════════════════════════════
I/flutter (11476): The following assertion was thrown resolving an image codec:
I/flutter (11476): Unable to load asset: assets/clouds-0.png
I/flutter (11476): 
I/flutter (11476): When the exception was thrown, this was the stack:
I/flutter (11476): #0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:230)
I/flutter (11476): <asynchronous suspension>
I/flutter (11476): #1      AssetBundleImageProvider._loadAsync (package:flutter/src/painting/image_provider.dart:384)
I/flutter (11476): <asynchronous suspension>
I/flutter (11476): #2      AssetBundleImageProvider.load (package:flutter/src/painting/image_provider.dart:369)
I/flutter (11476): #3      ImageProvider.resolve.<anonymous closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:266)
I/flutter (11476): #4      ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:82)
I/flutter (11476): #5      ImageProvider.resolve.<anonymous closure> (package:flutter/src/painting/image_provider.dart:266)
I/flutter (11476): (elided 8 frames from package dart:async)
I/flutter (11476): 
I/flutter (11476): Image provider: AssetImage(bundle: PlatformAssetBundle#d165f(), name: "assets/clouds-0.png")
I/flutter (11476): Image key: AssetBundleImageKey(bundle: PlatformAssetBundle#d165f(), name: "assets/clouds-0.png",
I/flutter (11476): scale: 1.0)
I/flutter (11476): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (11476): Another exception was thrown: Unable to load asset: assets/clouds-1.png
I/flutter (11476): Another exception was thrown: Unable to load asset: assets/ray.png
I/flutter (11476): Another exception was thrown: Unable to load asset: assets/sun.png
I/flutter (11476): Another exception was thrown: Unable to load asset: assets/weathersprites.png
I/flutter (11476): Another exception was thrown: Unable to load asset: assets/icon-sun.png
I/flutter (11476): Another exception was thrown: Unable to load asset: assets/icon-rain.png
I/flutter (11476): Another exception was thrown: Unable to load asset: assets/icon-snow.png

**Comment by vlidholt** [comment]
Fixed
