### ISSUE TITLE
Flutter/Flutter.h not found when built with Cocoapods 1.5

### ISSUE THREAD

**Issue by ngocdaothanh** [spritewidget/spritewidget#22]
The examples (including [spaceblast](https://github.com/spritewidget/spaceblast)) have "Flutter/Flutter.h not found" problem when built with Cocoapods 1.5, as explained at https://github.com/flutter/flutter/issues/16036.

As explained at the link above, please update all `Podfile` files with `Podfile-swift`:
https://github.com/flutter/flutter/tree/master/packages/flutter_tools/templates/cocoapods

**Comment by vlidholt** [comment]
Fixed
