### ISSUE TITLE
Eliminate uses of deprecated CONSTANTS

### ISSUE THREAD

**Issue by leafpetersen** [spritewidget/spritewidget#27]
This package uses the deprecated SCREAMING CAPS CONSTANTS which are about to be removed for Dart 2 (specifically UTF8). This tool is available for the migration: https://github.com/dart-lang/dart2_fix .

See https://groups.google.com/forum/#!topic/flutter-dev/PAhWVX2PIzA for more context.

**Comment by vlidholt** [comment]
Fixed
