### ISSUE TITLE
TexturedLine

### ISSUE THREAD

**Issue by AndyAstrand** [spritewidget/spritewidget#41]
So I'm trying to use the TexturedLine() class. I've searched for examples, I've poured over what there is of the documentation. I've failed to get it to produce any output. Then I've noticed the paint method of TexturedLine() currently says this:

`//TODO: Fix
//canvas.drawVertices(VertexMode.triangles, vertices, textureCoordinates, verticeColors, BlendMode.modulate, indices, _cachedPaint);`

I'm guessing this explains my failures. Are there any plans to get this implemented? Or should I try and roll my own?

**Comment by reducedcarpet** [comment]
I had to change that line a little, looks like the api has changed down the line slightly: 

`//TODO: Fix
    //canvas.drawVertices(VertexMode.triangles, vertices, textureCoordinates, verticeColors, BlendMode.modulate, indices, _cachedPaint);
    canvas.drawVertices(ui.Vertices(VertexMode.triangles, vertices, textureCoordinates: textureCoordinates, colors: verticeColors, indices: indices), BlendMode.modulate, _cachedPaint);`

and show the Vertices class in spritewidget.dart:

`import 'dart:ui' as ui show Image, Vertices;`

**Comment by vlidholt** [comment]
Fixed in latest release
