### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by arturomf** [spritewidget/spritewidget#44]
I'm wondering if this project is abandoned or it's in development.

I have been using Phaser.io to develop games in HTML5/Javascript and Spritewidget seemed something very similar but it lacks some important functions like path animation for example.

I have been able to develop almost all of my game functionality in SpriteWidget/Flutter but i'd like to know if there is any intention of further developing.

Best Regards!

**Comment by vlidholt** [comment]
It's now alive!
