### ISSUE TITLE
Apple reject 

### ISSUE THREAD

**Issue by namtruongsg** [spritewidget/spritewidget#48]
I have the problem when upload the game to apple store when use this framework as the main graphics engine

4. 7 Design: HTML5 Games, Bots, etc.
Guideline 4.7 - Design - HTML5 Games, Bots, etc.

We noticed that your app offers HTML5-based games, but the games appear to be an incidental feature that do not deeply enhance or enrich the user’s experience. 

Next Steps

To resolve this issue, please remove any HTML5-based games from your app that are not directly related to your app’s core functionality.

Please see attached screenshot for details.

.
![attachment-3334981558162093448Screenshot-0528-093750](https://user-images.githubusercontent.com/26561926/58526955-fd1f3a00-81fa-11e9-807e-bc7a54278637.png)

**Comment by vlidholt** [comment]
This seem not to be an issue related to SpriteWidget.
