### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by nisimjoseph** [spritewidget/spritewidget#54]
Can you provide which Licensing type is this project?
I want to use it inside my project and don't know what I can do with it.

is it MIT license?

**Comment by obitodarky** [comment]
@nisimjoseph you can find the License [here](https://github.com/spritewidget/spritewidget/blob/master/LICENSE)

**Comment by vlidholt** [comment]
License is BSD 2.0 license. Same as for Flutter I believe.
