### ISSUE TITLE
SpriteBox::handleEvent The method doesn't override an inherited method.

### ISSUE THREAD

**Issue by arisbartee** [spritewidget/spritewidget#60]
In sprite_box.dart handleEvent doesn't over ride a method in a parent class. And the signature for renderbox does not match.
@override
  void handleEvent(PointerEvent event, _SpriteBoxHitTestEntry entry) {....}

I believe this is causing my Nodes to not respond to event.s

**Comment by dsyrstad** [comment]
I believe it does, in fact, override the superclass method. It overrides `RenderBox.handleEvent()`. The signature matches since `_SpriteBoxHitTestEntry` is derived from `BoxHitTestEntry`.

**Comment by vlidholt** [comment]
Event handling seem to work. I'm closing this one. Please re-open with more info if this is still an issue.
