### ISSUE TITLE
FormatException

### ISSUE THREAD

**Issue by ever-deng** [spritewidget/spritewidget#69]

**Comment by ever-deng** [comment]
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Exception: FormatException: Unexpected extension byte (at offset 0)
E/flutter (19225): #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1783:7)
E/flutter (19225): #1      Utf8Decoder.convert (dart:convert/utf.dart:321:42)
E/flutter (19225): #2      Utf8Codec.decode (dart:convert/utf.dart:62:20)
E/flutter (19225): #3      AssetBundle._utf8decode (package:flutter/src/services/asset_bundle.dart:83:17)
E/flutter (19225): #4      _IsolateConfiguration.apply (package:flutter/src/foundation/_isolates_io.dart:81:34)
E/flutter (19225): #5      _spawn.<anonymous closure> (package:flutter/src/foundation/_isolates_io.dart:88:65)
E/flutter (19225): #6      Timeline.timeSync (dart:developer/timeline.dart:163:22)
E/flutter (19225): #7      _spawn (package:flutter/src/foundation/_isolates_io.dart:85:35)
E/flutter (19225): #8      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:304:17)
E/flutter (19225): #9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

**Comment by vlidholt** [comment]
Need more info on this one. May have been fixed in 2.0 release. Please reopen if issue still is there.
