### ISSUE TITLE
Null safety version

### ISSUE THREAD

**Issue by TheKashe** [spritewidget/spritewidget#70]
Hi everyone,

i've migrated spritewidget to null safety version, available [here](https://github.com/TheKashe/spritewidget/tree/nullsafety) on nullsafety branch.

The codebase is my slightly modified version with some minor bugfixes, check version history to see how it differs from spritewidget master.

Regarding nullsafety, I've done very conservative migration with as little changes as possible. Original codebase is using some patterns which are IMO not the best practice with the current dart version, but I didn't touch that. On the plus side, there was a lot of null checks in the code base, so now nullable variables should make no problems.

The biggest issue is that some fields are initialised late through some kind of state transitions. I did not analyse if everything is initialised properly, but my app and the examples work.

I use a small subset of spritewidget in my project so some parts could break, mostly the late variables. In some cases I did't know how to handle null value and went with what seems sensible default (e.g. Offset.zero or double 0.0). Not sure on the potential effects.

Hope somebody finds it valuable.

**Comment by hsnbsst** [comment]
+1

**Comment by mirrorlink** [comment]
lovely! tks

**Comment by w-e-b-t-e-c-s** [comment]
Great, this works for me too. When is this going to be proposed as a pull request ?

**Comment by vlidholt** [comment]
SpriteWidget now has official null safety support. 2.0 release coming soon!
