### ISSUE TITLE
Feature request. Camera

### ISSUE THREAD

**Issue by Grabli66** [spritewidget/spritewidget#9]
Camera with:
+ Follow object
+ Zoom
+ Shake screen

**Comment by vlidholt** [comment]
@Grabli66 this is pretty much already supported using the node tree. Just place all your game objects below a single `Node`. When you move/scale/shake that `Node` it affects all sprites and objects under it. A shake effect hasn't been implemented, but it'd be pretty easy using the `Action` API. You can use constraints to follow an object.
